-- Verifies that the disable_full_refresh property prevents table replacement.
-- This test inspects the build plan generated by get_source_build_plan for the
-- test_source_table_no_full_refresh source. When full_refresh_mode would be true,
-- the disable_full_refresh flag should override it to false, meaning the build plan
-- should NOT contain any DROP TABLE statements for an existing table.

{% set source_nodes = graph.sources.values() if graph.sources else [] %}
{% set source_node = none %}
{% for node in source_nodes %}
    {% if node.name == 'test_source_table_no_full_refresh' %}
        {% set source_node = node %}
    {% endif %}
{% endfor %}

{% if source_node is none %}
    {# Source not found - skip test gracefully (e.g. during run-operation) #}
    SELECT 1 WHERE 1 = 0
{% else %}

{% if not source_node.external.get('disable_full_refresh', false) %}
    {{ exceptions.raise_compiler_error("disable_full_refresh property is not set to true on test_source_table_no_full_refresh") }}
{% endif %}

-- Get the build plan (first run) - this simulates what happens during on-run-start
-- The table already exists (created by initial run), so with full_refresh the normal
-- behavior would be to drop it. With disable_full_refresh, it should skip the drop.
{% set build_plan = dbt_dataengineers_materializations.get_source_build_plan(source_node, true, 'internal', true) %}

-- Check that no statement in the build plan contains DROP TABLE for our target table
{% set has_drop = [] %}
{% for stmt in build_plan %}
    {% if 'DROP TABLE' in stmt | upper and 'TEST_SOURCE_TABLE_NO_FULL_REFRESH' in stmt | upper %}
        {% do has_drop.append(true) %}
    {% endif %}
{% endfor %}

-- This test returns rows on FAILURE. If disable_full_refresh is working correctly,
-- there should be no DROP statement, so has_drop should be empty.
SELECT 1
WHERE {{ has_drop | length }} > 0

{% endif %}
